inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - tmp/**/*
    - vendor/**/*

SpecialGlobalVars:
  Enabled: false

AsciiComments:
  Enabled: false

ClassLength:
  Max: 200

Documentation:
  Enabled: false

LineLength:
  Max: 137
  Exclude:
    - spec/**/*

PerlBackrefs:
  Enabled: false

TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

